/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ausport;

import java.util.List;

import ausport.model.Gender;
import ausport.model.Role;
import ausport.model.User;
import ausport.model.UserDAOImpl;


// import ausport.model.*;
// import ausport.util.PasswordHelper;
// import static ausport.model.Role.ADMIN;

public class App {

    public static void main(String[] args) {

    }

}
